site_name: BetokenJS Docs
theme: readthedocs
nav:
  - Home: index.md
  - API Reference:
    - betoken.timer: api/timer.md
    - betoken.user: api/user.md
    - betoken.tokens: api/tokens.md
    - betoken.stats: api/stats.md
    - betoken.refreshActions: api/refresh.md
    - betoken.investorActions: api/investor-actions.md
    - betoken.managerActions: api/manager-actions.md